/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    copy: typeof import('./src/modules/content-reel/components/post/PostItemOptions copy.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FetchError: typeof import('./src/components/FetchError.vue')['default']
    FlaggedSigninMessage: typeof import('./src/components/FlaggedSigninMessage.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MyAvatar: typeof import('./src/components/MyAvatar.vue')['default']
    MyIcon: typeof import('./src/components/MyIcon.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    Post: typeof import('./src/modules/content-reel/components/post/Post.vue')['default']
    PostCreator: typeof import('./src/modules/content-reel/components/post/PostCreator.vue')['default']
    PostCreatorMediaAttachment: typeof import('./src/modules/content-reel/components/post/PostCreatorMediaAttachment.vue')['default']
    PostItem: typeof import('./src/modules/content-reel/components/post/PostItem.vue')['default']
    PostItemHeader: typeof import('./src/modules/content-reel/components/post/PostItemHeader.vue')['default']
    PostItemIcon: typeof import('./src/modules/content-reel/components/post/PostItemIcon.vue')['default']
    PostItemIcons: typeof import('./src/modules/content-reel/components/post/PostItemIcons.vue')['default']
    PostItemOptionCopyLink: typeof import('./src/modules/content-reel/components/post/PostItemOptionCopyLink.vue')['default']
    PostItemOptions: typeof import('./src/modules/content-reel/components/post/PostItemOptions.vue')['default']
    PostItemOptionToggleFollow: typeof import('./src/modules/content-reel/components/post/PostItemOptionToggleFollow.vue')['default']
    PostItemSkeleton: typeof import('./src/modules/content-reel/components/skeletons/PostItemSkeleton.vue')['default']
    ReelNavbar: typeof import('./src/modules/content-reel/components/shared/ReelNavbar.vue')['default']
    ReelNavbarMobile: typeof import('./src/modules/content-reel/components/shared/ReelNavbarMobile.vue')['default']
    ReelRightSidebar: typeof import('./src/modules/content-reel/components/ReelRightSidebar.vue')['default']
    ReelRightSidebarItem: typeof import('./src/modules/content-reel/components/ReelRightSidebarItem.vue')['default']
    ReelRightSidebarSkeleton: typeof import('./src/modules/content-reel/components/skeletons/ReelRightSidebarSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SimpleError: typeof import('./src/components/SimpleError.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SwitchCase: typeof import('./src/components/switch-case/SwitchCase.vue')['default']
    SwitchCaseItem: typeof import('./src/components/switch-case/SwitchCaseItem.vue')['default']
    Textbox: typeof import('./src/components/Textbox.vue')['default']
    UserMention: typeof import('./src/modules/content-reel/components/UserMention.vue')['default']
  }
}
